<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_uncertain_w-100 h-auto</name>
   <tag></tag>
   <elementGuidId>f916e05e-5c9a-47bb-b2e5-a5aaf0c38e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item.filter.8.upl-img > div.bg-warning > img.w-100.h-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='medialibrary']/div[3]/div[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8183d2de-67f0-4485-9ad5-bd341f5b5d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.cognispark.ai/storage/composer/medialibrary/vUqcBX9F0uyfnoKT.png</value>
      <webElementGuid>7157d16c-af1b-449e-b7b2-2150b0f4ff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e94033ce-a59d-4c43-8460-061d095ee06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-json</name>
      <type>Main</type>
      <value>{&quot;title&quot;:null,&quot;path&quot;:&quot;\/storage\/composer\/medialibrary\/vUqcBX9F0uyfnoKT.png&quot;,&quot;url&quot;:&quot;\/storage\/composer\/medialibrary\/vUqcBX9F0uyfnoKT.png&quot;,&quot;duration&quot;:&quot;&quot;,&quot;preview&quot;:&quot;https:\/\/dev.cognispark.ai\/storage\/composer\/medialibrary\/vUqcBX9F0uyfnoKT.png&quot;,&quot;extension&quot;:&quot;png&quot;,&quot;thumbnail_path&quot;:&quot;https:\/\/dev.cognispark.ai\/storage\/composer\/medialibrary\/vUqcBX9F0uyfnoKT.png&quot;,&quot;id&quot;:271,&quot;mime_type&quot;:&quot;image\/png&quot;,&quot;height&quot;:800,&quot;width&quot;:400,&quot;category_id&quot;:8,&quot;keywords&quot;:&quot;standing,champion,cheer&quot;}</value>
      <webElementGuid>ed4f13d5-1996-488e-b5df-393a336f9758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-auto </value>
      <webElementGuid>a12f195b-6302-46db-a66b-4c571f00c951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medialibrary&quot;)/div[@class=&quot;un-pix we-scroll&quot;]/div[@class=&quot;upload-images we-scroll&quot;]/div[@class=&quot;item filter 8 upl-img&quot;]/div[@class=&quot;bg-warning&quot;]/img[@class=&quot;w-100 h-auto&quot;]</value>
      <webElementGuid>124a929b-75a4-4859-ab18-dce44685061f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='medialibrary']/div[3]/div[3]/div/div/img</value>
      <webElementGuid>d03ec311-a636-4b4d-adc0-4f9fb9721080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='8']</value>
      <webElementGuid>a4889903-cb19-459c-9242-1700c423635c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/img</value>
      <webElementGuid>cb8c5022-7a68-42ab-bdea-0765603d02f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.cognispark.ai/storage/composer/medialibrary/vUqcBX9F0uyfnoKT.png' and @alt = '8']</value>
      <webElementGuid>8bbe6364-366a-437b-b57f-30cb586e8cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
