<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1</name>
   <tag></tag>
   <elementGuidId>9c8b6748-f66f-48b8-98ed-0277989a1dbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#without_knowledgebase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='without_knowledgebase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bab25a9f-7152-4dc0-ab0f-45c6c52afa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b7a743fa-118b-4c43-9bb7-ddb59cae0078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>without_knowledgebase</value>
      <webElementGuid>6195ee97-f7f9-4db3-a645-43ffbd60d90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn creation w-100</value>
      <webElementGuid>02cfa2a7-8f26-4c77-99ad-28ce67834be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next </value>
      <webElementGuid>95c30cc4-d1aa-492c-b064-a5f33b5bd4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;without_knowledgebase&quot;)</value>
      <webElementGuid>8a87b1ad-2042-4238-8513-438b05655821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='without_knowledgebase']</value>
      <webElementGuid>4cfc0f03-3904-416e-8905-392dfb349df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='withoutKnowledgeBaseForm']/button</value>
      <webElementGuid>b9daf96a-7939-44a3-a0c2-8495986a7d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload New Data'])[1]/following::button[1]</value>
      <webElementGuid>4f2c27ea-56f7-4801-9c6c-f464f591125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[1]</value>
      <webElementGuid>dd2e394a-c0b8-4d2a-b216-fd1afa4506cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Knowledge Base'])[1]/preceding::button[1]</value>
      <webElementGuid>c27c7e12-e8ee-478e-b832-5c52f7d29f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::button[2]</value>
      <webElementGuid>bf9ece87-ae87-4973-bff3-d8844ecf3c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>b08bc7bf-7f09-42f7-960b-5dd5a95aaca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'without_knowledgebase' and (text() = 'Next ' or . = 'Next ')]</value>
      <webElementGuid>ba472259-c19b-45d5-ae35-127f50dea41e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
