<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(The primary objective your AI Chatbo_012db7</name>
   <tag></tag>
   <elementGuidId>90dbd22b-2b87-43c0-b3ba-e40e2fe52a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#asst_purpose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='asst_purpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1957ce5b-477f-433a-bffa-1784a86be47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02e786c0-8aaf-4082-a584-a4049ada8cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96a7d043-f73c-44b3-899a-8562ef572c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asst_purpose</value>
      <webElementGuid>f9f04c71-99ca-4d4e-8900-79fd9f2306bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asst_purpose</value>
      <webElementGuid>bf3f0e2e-1d6e-41d7-8e8e-0bd4726d0199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter purpose</value>
      <webElementGuid>7e7ab4ca-ef26-4a1b-a62b-a77e78a632e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asst_purpose&quot;)</value>
      <webElementGuid>075592bd-59f1-4047-a4b4-6a2e55a3f08d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='asst_purpose']</value>
      <webElementGuid>aa25455b-0d81-4a52-bd2c-49f1bf1e87b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div[2]/div/div/input</value>
      <webElementGuid>b2b26b30-fa58-469a-a099-caa9e686e5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9cc88c94-82c9-4283-b5bd-7f2886af7c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'asst_purpose' and @name = 'asst_purpose' and @placeholder = 'Enter purpose']</value>
      <webElementGuid>06b6278a-1adf-4326-a75b-519409226430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
