<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(The title or identity of your AI Cha_23e70a</name>
   <tag></tag>
   <elementGuidId>2a3fe04e-9945-4919-a078-4a5cdda4808b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#asst_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='asst_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c41150b-7951-4192-b193-fc23c6785520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87b63acc-b82e-4012-b1a2-95d51e406f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d93f0089-34fd-42fe-98db-949a2ee6b002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asst_name</value>
      <webElementGuid>354070da-44e1-460e-9918-38f847c45aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asst_name</value>
      <webElementGuid>3de2b7fe-7a68-40ac-8243-3b08b1c70c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>5f9728f6-f881-4021-a4e5-8a7a367c5529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Name of chatbot</value>
      <webElementGuid>8edebb9c-ac7d-43f3-a90d-0885e2a73cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asst_name&quot;)</value>
      <webElementGuid>d7e2b627-8280-4d2b-8237-92c19e474464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='asst_name']</value>
      <webElementGuid>2589f157-896a-4215-849b-8f544ff66ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div/div/div/input</value>
      <webElementGuid>bca27b4f-a0c3-44ca-99ee-d3eb8ddc5406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2c35221b-9a78-457a-8f87-add5afa6d015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'asst_name' and @name = 'asst_name' and @placeholder = 'Enter Name of chatbot']</value>
      <webElementGuid>d8ba615b-e292-44a9-aa93-573306e886b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
