<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fallback Response_asst_fallback_resp</name>
   <tag></tag>
   <elementGuidId>273ddb38-1de8-4613-9432-67efdc414c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#asst_fallback_resp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='asst_fallback_resp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30565fdd-191a-437a-a454-72be7b69788b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a59a54a4-07bc-4358-b103-df8f3436bcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f275040a-172c-426c-9842-3caaf6c54edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asst_fallback_resp</value>
      <webElementGuid>3b762929-0be8-40d4-a0f2-7fb4b281fb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asst_fallback_resp</value>
      <webElementGuid>d05394c9-fadc-4a46-81e2-71bc85908d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Fallback Response</value>
      <webElementGuid>241e2fbf-68e6-448c-846f-d87c19405cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asst_fallback_resp&quot;)</value>
      <webElementGuid>806d827b-08da-4ed3-8d3c-d5f56ec43913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='asst_fallback_resp']</value>
      <webElementGuid>8a5d23ab-3b3d-46e1-9be1-6e5d5cb15737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div[3]/div/div/input</value>
      <webElementGuid>66c9ea6e-0af8-420b-adf3-563a61079658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c61f2ba2-8e2f-4f7d-a9be-7a556d7b258a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'asst_fallback_resp' and @name = 'asst_fallback_resp' and @placeholder = 'Enter Fallback Response']</value>
      <webElementGuid>f4d522ec-1467-4acb-a657-16950d2ed889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
