<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Docx</name>
   <tag></tag>
   <elementGuidId>70bfdedb-7858-41e1-9a36-4530222698f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapsibleNavbar']/ul/li[3]/ul/li[3]/div/ul/div/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fddfbf84-9c2e-46fd-886f-5b939792301e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.cognispark.ai/exportdoc/3G4qL0om1gw4f9aW</value>
      <webElementGuid>ce401585-c809-47d7-97b9-0b1db1a47632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>ca735c88-d571-484f-bbba-67203f2d6b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Docx</value>
      <webElementGuid>47bcd51c-d5bf-4abc-a02a-904132c25301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleNavbar&quot;)/ul[@class=&quot;navbar-nav outer&quot;]/li[@class=&quot;nav-item third&quot;]/ul[@class=&quot;navbar-nav align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;btn-group dropstart dot-drop px-3 show&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-end multi-level mt-3 show&quot;]/div[@class=&quot;action text-left&quot;]/li[@class=&quot;dropdown-submenu&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>8dd0af39-9091-4825-bb9e-dceb7833bfea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapsibleNavbar']/ul/li[3]/ul/li[3]/div/ul/div/li[2]/a</value>
      <webElementGuid>e9558290-598c-4256-bdbf-fd037b29c8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Docx')]</value>
      <webElementGuid>d31cdc54-61b1-4a1d-9f58-2470635a026a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/following::a[2]</value>
      <webElementGuid>3c70e9ed-cd33-48fa-8767-753ab050bc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockquote'])[1]/preceding::a[2]</value>
      <webElementGuid>202e1fe4-8645-4a37-ac81-fe5f9b910c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/preceding::a[3]</value>
      <webElementGuid>30cfcc6b-7204-4d6c-85c6-5769348062ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Docx']/parent::*</value>
      <webElementGuid>88b1eddb-6af0-457b-aa72-e1559e567e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://dev.cognispark.ai/exportdoc/3G4qL0om1gw4f9aW')])[2]</value>
      <webElementGuid>4ef9bfea-9a62-4536-a628-91c96a8aa8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[2]/a</value>
      <webElementGuid>a841fbb7-b940-4fcf-9818-896624f4da58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.cognispark.ai/exportdoc/3G4qL0om1gw4f9aW' and (text() = 'Docx' or . = 'Docx')]</value>
      <webElementGuid>3d0b22d1-7baf-4f24-8cb3-6944c3a6c1b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
