<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PDF</name>
   <tag></tag>
   <elementGuidId>17b23cdb-4207-43d7-9288-2a59c42c98a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapsibleNavbar']/ul/li[3]/ul/li[3]/div/ul/div/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57dd3632-7017-4030-8625-ce9c19f293ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.cognispark.ai/exportpdf/3G4qL0om1gw4f9aW</value>
      <webElementGuid>45dd63f5-0c54-4499-9800-6c527109ab60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>43778b85-9b5a-481d-b183-cd4ddcd8ebd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                PDF</value>
      <webElementGuid>16040994-61fe-4095-bcff-3f49cd37acba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleNavbar&quot;)/ul[@class=&quot;navbar-nav outer&quot;]/li[@class=&quot;nav-item third&quot;]/ul[@class=&quot;navbar-nav align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;btn-group dropstart dot-drop px-3 show&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-end multi-level mt-3 show&quot;]/div[@class=&quot;action text-left&quot;]/li[@class=&quot;dropdown-submenu&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>2eae5089-de9c-49de-972b-81601579cdce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapsibleNavbar']/ul/li[3]/ul/li[3]/div/ul/div/li/a</value>
      <webElementGuid>674870f0-9ff2-4470-8bb2-078f1ec2d3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/following::a[1]</value>
      <webElementGuid>3e4a5544-3225-4d2c-87d2-e0d9ba174364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[2]</value>
      <webElementGuid>b2c16892-ddee-4280-b772-9c6131bae467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docx'])[1]/preceding::a[1]</value>
      <webElementGuid>156a40a1-bd4f-48ee-b961-b39bb8763ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockquote'])[1]/preceding::a[3]</value>
      <webElementGuid>ba76c2c8-5bcd-43a3-81bf-d0ea0875840e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PDF']/parent::*</value>
      <webElementGuid>0a2f038f-b66c-4973-b408-20fcf56d2d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.cognispark.ai/exportpdf/3G4qL0om1gw4f9aW')]</value>
      <webElementGuid>97ed370a-9f65-4e42-aa17-56abbe47ac11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/a</value>
      <webElementGuid>4284fe6e-885a-4e19-901b-796408792dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.cognispark.ai/exportpdf/3G4qL0om1gw4f9aW' and (text() = '
                                                PDF' or . = '
                                                PDF')]</value>
      <webElementGuid>40c154b0-d227-4cf7-9245-d68620883019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
