<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2. Understanding Ethical Behavior</name>
   <tag></tag>
   <elementGuidId>5be044f8-0c96-4cd3-947d-43ed8559be41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='headingOne'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a422d5c0-19c9-41d4-81ae-8fa0979bf57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>8c50210d-1f2a-40ef-be22-124a14d2cc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headingOne</value>
      <webElementGuid>f062b818-0557-489e-a5a1-5388305c16f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>cdb45fd2-42a5-43ab-8558-9abd80443c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse1</value>
      <webElementGuid>e8e82d22-22c1-4407-a2ce-a566399be025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cdad2386-99b9-41d1-9333-b99253a6d94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse1</value>
      <webElementGuid>bfb95a97-d29e-4f1f-b77b-a2d00a5ebca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    2. Understanding Ethical Behavior
            </value>
      <webElementGuid>18a87066-5db6-4fef-9422-711219a85191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableOfContents&quot;)/div[@class=&quot;card mt-2&quot;]/div[@id=&quot;headingOne&quot;]</value>
      <webElementGuid>74bb479b-ba68-45d9-be2b-713718f3db20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='headingOne'])[2]</value>
      <webElementGuid>456da8c3-7cb6-493f-bc99-a2312d89b1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TableOfContents']/div[2]/div</value>
      <webElementGuid>c212f1ea-f373-4471-8089-e751661c7aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docx'])[1]/following::div[9]</value>
      <webElementGuid>7d9edcee-8d40-43e0-96e4-81bf8f366b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockquote'])[1]/preceding::div[41]</value>
      <webElementGuid>34a45f50-1367-4eed-beb2-2675fad221c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/preceding::div[41]</value>
      <webElementGuid>51f3deeb-eb1e-4678-afb7-7bc9c7f76904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2. Understanding Ethical Behavior']/parent::*</value>
      <webElementGuid>ea276072-eef0-4de0-ad0f-b6528cde8d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>b6b476ef-8968-4dca-8202-67253f9cb933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headingOne' and (text() = '
                    2. Understanding Ethical Behavior
            ' or . = '
                    2. Understanding Ethical Behavior
            ')]</value>
      <webElementGuid>f543c6b8-cc02-4737-85ef-88eb7d9782e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
