<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3. Applying the Code of Conduct</name>
   <tag></tag>
   <elementGuidId>e937161b-0457-4ede-92cb-61127814ac28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='headingOne'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55cd7047-3a30-4aab-8edf-4edea8fee2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>e841cbe6-817c-4fbc-ae43-519ff74144f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headingOne</value>
      <webElementGuid>a69432b7-8d3f-4ffd-bacc-d934c8dd29c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>5c29a924-e4ec-4bf6-9bf9-7916a3eccd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse2</value>
      <webElementGuid>8e4ed001-30b8-4900-8d28-f151524a83d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01929bf3-c402-4b7b-8ab9-6fa2888eb610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse2</value>
      <webElementGuid>92e21a81-28d7-4f3c-81a7-9d856a37a02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    3. Applying the Code of Conduct
            </value>
      <webElementGuid>7c5d1359-46d7-4b46-aa6b-190977d7b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableOfContents&quot;)/div[@class=&quot;card mt-2&quot;]/div[@id=&quot;headingOne&quot;]</value>
      <webElementGuid>4319e263-5835-40f6-89f0-16315a3b3184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='headingOne'])[3]</value>
      <webElementGuid>54515bc1-d7df-4f76-9f88-a449135a5898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TableOfContents']/div[3]/div</value>
      <webElementGuid>72e1061c-e1ab-44fb-8108-3c339e5e0889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docx'])[1]/following::div[13]</value>
      <webElementGuid>b972d10d-564a-4bee-96bd-ee1114e60bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockquote'])[1]/preceding::div[37]</value>
      <webElementGuid>921020fc-bc4b-4534-bd73-3f683f7ff9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/preceding::div[37]</value>
      <webElementGuid>f80dcf85-3606-4d1b-bd29-14876fcfd72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3. Applying the Code of Conduct']/parent::*</value>
      <webElementGuid>317519dd-1125-44ac-bdb0-e62ca2a3b6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>2d5a9ca9-8397-49b8-9409-9d1b4ecba10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headingOne' and (text() = '
                    3. Applying the Code of Conduct
            ' or . = '
                    3. Applying the Code of Conduct
            ')]</value>
      <webElementGuid>c08a2f31-81a7-41c1-96f7-85033f9f6572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
