<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoviceAdvanced BeginnerCompetentProf_e0f65a</name>
   <tag></tag>
   <elementGuidId>6f5a540e-e622-4e3a-97f4-b9a7693b9271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='skilllevel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#skilllevel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ac40bb33-0ee0-40ea-9ccd-338d36b50511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skilllevel</value>
      <webElementGuid>e97b6680-da4a-43de-b26a-97d256bc872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skilllevel</value>
      <webElementGuid>92e7b1cc-f731-4334-8a18-ebb61fb4cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-box</value>
      <webElementGuid>4c54a225-0e87-4593-860a-e344667b7865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											</value>
      <webElementGuid>6a319963-abea-4f73-9ff0-b1617d6608a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skilllevel&quot;)</value>
      <webElementGuid>b457e477-ba4a-4ccd-b591-fe17342aa6f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='skilllevel']</value>
      <webElementGuid>a9cf0c39-70fb-4ff1-a2aa-006dca4406fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='obj_outc']/div/div[2]/div/select</value>
      <webElementGuid>fc99cf5a-a2c6-4271-9850-33d135bfabd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audience'])[1]/following::select[1]</value>
      <webElementGuid>7628d035-08ec-4e47-9412-e30dfc1a639d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[1]/preceding::select[1]</value>
      <webElementGuid>6dc0f761-5630-4572-aaf4-6c3679ada638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/preceding::select[2]</value>
      <webElementGuid>e6b9b93e-a228-4404-a0a2-89fc39963928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f6785597-000d-41f2-ad56-3b86e329d923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'skilllevel' and @name = 'skilllevel' and (text() = '
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											' or . = '
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											')]</value>
      <webElementGuid>02d97689-95ff-44f3-9c09-103aaad9108d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
