<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Open_course</name>
   <tag></tag>
   <elementGuidId>f817996a-9251-48f1-88f1-e4842beb1288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.embed-responsive.embed-responsive-16by9 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;card&quot;]/div[@onclick=&quot;window.open('https://dev.cognispark.ai/course/6sbfybBbiOEl9qdK/edit')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8444a84a-6707-4036-97f7-f54715076be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/storage/composer/courses/6sbfybBbiOEl9qdK/files/thumbnail.png?time=1741334336195</value>
      <webElementGuid>06e448d0-e747-4bee-82a3-150775471b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;videoListView&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9&quot;]/img[1]</value>
      <webElementGuid>ffe3fab7-2790-4e3a-816d-647dfab61051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='videoListView']/div/div/img</value>
      <webElementGuid>be3b652e-9a08-4247-8779-214466d2fbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>3241449a-38c2-424e-94be-e1aed0899089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/storage/composer/courses/6sbfybBbiOEl9qdK/files/thumbnail.png?time=1741334336195']</value>
      <webElementGuid>34c83cef-ae4f-4f3f-91df-28cbdaf5e0fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
