<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add new slide_radioValue</name>
   <tag></tag>
   <elementGuidId>a1917ec1-1cb4-4a12-9c9c-9128af64ff6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='select_all_image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_all_image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9193ea8-293b-4d02-b96a-454cf0a958a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bd0f044f-32be-41a7-bb97-c6f16b77e8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_all_image</value>
      <webElementGuid>308b52dc-907f-4ce8-8320-7732c638a463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioValue</value>
      <webElementGuid>3ff11bab-ca65-4ff4-a672-776d95690508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_all_image&quot;)</value>
      <webElementGuid>7da33d68-ace5-4d91-8897-faf22e4d6f0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='select_all_image']</value>
      <webElementGuid>8c50b85b-8080-49a7-8f34-bc14400031eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sld_nos']/div/div/span/input</value>
      <webElementGuid>b61d3c83-b812-4621-8bb9-961b974cabed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>9f8e0e1c-4fcf-4b51-8999-f4e48e1ad8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'select_all_image' and @name = 'radioValue']</value>
      <webElementGuid>31e791a3-bd5f-4ef7-8b45-bce516a6faf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
