<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create AI Chatbots</name>
   <tag></tag>
   <elementGuidId>6cbd091d-529f-4aaf-8f96-142b10c25601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-chatbot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='create-chatbot']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06691347-f67f-45d2-897a-db7325643f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>038f2f11-046c-4782-8942-1c377fa37ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-chatbot</value>
      <webElementGuid>eda97687-8fd4-4472-8124-0d772fa8a01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary px-3</value>
      <webElementGuid>20b37ee5-f852-4315-bac4-a96050f7ab48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create AI Chatbots</value>
      <webElementGuid>7aad19ac-cab6-4d9d-88ce-42d5b913f373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-chatbot&quot;)</value>
      <webElementGuid>01f8de8f-253d-4afd-8324-51efa4eb7f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='create-chatbot']</value>
      <webElementGuid>0d3e6a7b-93ac-4cc0-8c5f-df49d2d8a2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create AI Chatbots')]</value>
      <webElementGuid>b9147840-9feb-4f97-bb67-8acc5b456186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create AI Chatbots'])[1]/following::a[1]</value>
      <webElementGuid>33dbb751-3551-4361-bde2-83ad5e961f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe Now!'])[1]/following::a[1]</value>
      <webElementGuid>bd3a63aa-ed31-4564-a53c-b55f9e9aee49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::a[1]</value>
      <webElementGuid>6b8ece37-c7c0-4207-a187-3edd59dabcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::a[3]</value>
      <webElementGuid>1818fbf2-d9c7-488d-9f6e-d76fdf2861cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>245c4b76-5887-417a-8a49-14e816191847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>1c47d3b8-18fe-4300-aa7d-44cf0441411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'create-chatbot' and (text() = 'Create AI Chatbots' or . = 'Create AI Chatbots')]</value>
      <webElementGuid>154f4c3c-2fb1-4f1e-ba60-26a1363160a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
