<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_V.Flip</name>
   <tag></tag>
   <elementGuidId>0d405642-2eaa-4f24-ad81-73de14843ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.up-img.vertical-flip-image.d-flex.align-items-center.justify-content-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f5d749f-f9d9-4351-85fe-9d3ad938ce95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb1487b6-63ab-4639-9e00-beb03c98ce01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn up-img vertical-flip-image  d-flex align-items-center justify-content-center</value>
      <webElementGuid>f4759abc-0f85-46c7-a84e-d4c02beeb4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  V.Flip</value>
      <webElementGuid>d6dd5926-c2b7-4a30-913c-579b1fbc926d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image-component-bar&quot;)/div[@id=&quot;accordionExample&quot;]/div[@class=&quot;btn-group-img pb-1 grid-btn-group&quot;]/button[@class=&quot;btn up-img vertical-flip-image  d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>15586b60-691d-45d5-abca-7fb8f9bbaa76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>71833ef0-53d7-4a4c-af50-ae8655faf084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionExample']/div[2]/button[5]</value>
      <webElementGuid>2af747cd-467e-4d5e-a8ee-eed369d018f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='V.Flip']/parent::*</value>
      <webElementGuid>63745f54-17f5-4d9b-a859-448c55648a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>6186e40f-fce3-4eac-984a-87398ddc95de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  V.Flip' or . = '  V.Flip')]</value>
      <webElementGuid>3ff4933c-6258-4c4f-b1d6-829d43d58d9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
