<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_d62828</name>
   <tag></tag>
   <elementGuidId>c146d178-fab4-4346-b099-63a6ec567439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clr-swatch-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='clr-swatch-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79b9e795-5fe1-4c22-b049-170217e2833d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b470e0b7-30c5-4038-9594-58d753e27247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clr-swatch-5</value>
      <webElementGuid>f61c4c68-2945-42f0-b2bb-7fb8062a68ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>clr-swatch-label clr-swatch-5</value>
      <webElementGuid>11eca0e4-6d2d-4a0b-9165-036a4b2392d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#d62828</value>
      <webElementGuid>b49e66b6-6bc5-45c8-be63-ec64b39c3d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clr-swatch-5&quot;)</value>
      <webElementGuid>5c2ab888-62da-4852-87fe-650b02c27c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='clr-swatch-5']</value>
      <webElementGuid>1d1e7702-1ba5-43e1-af87-4c54feb7996b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clr-swatches']/div/button[6]</value>
      <webElementGuid>0a732cc9-f13b-4521-b47a-1db06832baed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#e76f51'])[1]/following::button[1]</value>
      <webElementGuid>4481308e-f925-4b98-b142-6694338b1bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#f4a261'])[1]/following::button[2]</value>
      <webElementGuid>4aa2a77e-c78e-484f-8829-155b03ab3a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#023e8a'])[1]/preceding::button[1]</value>
      <webElementGuid>0e2ffeb7-3230-4b9f-a8cc-5fcf25934934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#0077b6'])[1]/preceding::button[2]</value>
      <webElementGuid>c1ac4566-4115-4fec-a54b-90dfeb3d2499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#d62828']/parent::*</value>
      <webElementGuid>e4fb3e6b-4332-45e1-b66f-d1b65da4e854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button[6]</value>
      <webElementGuid>e14bcb28-7771-49ae-9ac0-9567220ae508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'clr-swatch-5' and (text() = '#d62828' or . = '#d62828')]</value>
      <webElementGuid>a413f5b0-85ef-4e96-a2a6-e597a1635901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
