<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_H.Flip</name>
   <tag></tag>
   <elementGuidId>5333f186-d396-46b6-8238-8389c2c122af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.up-img.horizontal-flip-image.d-flex.align-items-center.justify-content-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd75f069-5439-4612-a268-7beef39d13f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3be512e-6687-4499-90b4-f93f8aafe576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn up-img horizontal-flip-image d-flex align-items-center justify-content-center</value>
      <webElementGuid>2aad7020-5290-4764-9594-c30c7db2a5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  H.Flip</value>
      <webElementGuid>ed724a84-c5fb-4c68-8a7a-330a6f7607ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image-component-bar&quot;)/div[@id=&quot;accordionExample&quot;]/div[@class=&quot;btn-group-img pb-1 grid-btn-group&quot;]/button[@class=&quot;btn up-img horizontal-flip-image d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>83e26a4e-ae8d-4472-b979-5806d7b332a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>5a99f5f7-7023-4a1f-9204-5c98fe73f4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionExample']/div[2]/button[4]</value>
      <webElementGuid>c1969235-31e7-4831-a129-3273364b33fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='H.Flip']/parent::*</value>
      <webElementGuid>1b80eb15-3b50-4a60-9258-2b9b8f7b8027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>5eb502d5-682b-45a0-9344-e3d6ce0f4b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  H.Flip' or . = '  H.Flip')]</value>
      <webElementGuid>e81b4ea8-41cd-4486-b0ad-bf3da36d3bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
