<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appearance</name>
   <tag></tag>
   <elementGuidId>092d1802-0226-4743-8b0e-e1f9bbfd3d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordionExample > div.accordion-item.appearance-tab > #headingOne > button.accordion-button.mt-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[366]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b99867b7-de2b-4490-8018-e7a7abd4b243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button mt-0</value>
      <webElementGuid>34e0128f-db44-4a8b-97ed-9ad66d0d7ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2db5cc9-7ee7-4e8b-bbd6-83b3fc03e012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>b4e7e8d9-cb8c-42f1-9809-abe17b114151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#collapseOne</value>
      <webElementGuid>87a8c1d3-ec25-4bb6-a8e8-ce6b39cd82e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b130f3cc-6158-4a15-be80-7729257a3f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseOne</value>
      <webElementGuid>ec3d2d46-6be5-410a-afd9-02291e4a0b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Appearance
                </value>
      <webElementGuid>0f85b08e-95b3-4fa7-a325-7db9745ac8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-component-bar&quot;)/div[@id=&quot;accordionExample&quot;]/div[@class=&quot;accordion-item appearance-tab&quot;]/h2[@id=&quot;headingOne&quot;]/button[@class=&quot;accordion-button mt-0&quot;]</value>
      <webElementGuid>c8652610-7d19-422c-a767-6e569e39c3de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[366]</value>
      <webElementGuid>3041884b-745a-40ec-a4ad-a5e38bce29ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//h2[@id='headingOne']/button)[8]</value>
      <webElementGuid>25c484e1-c874-4396-9ee3-ddf2a3ff034a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All Effects'])[1]/following::button[1]</value>
      <webElementGuid>8090ba78-09cb-4ecf-9246-6359ba482105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Flash Card'])[1]/following::button[1]</value>
      <webElementGuid>c5242383-8715-40f8-9ab1-9517222d41fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fill'])[1]/preceding::button[1]</value>
      <webElementGuid>1eb0e6f0-179f-4fe4-96b6-b28ee1bef189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Fill'])[1]/preceding::button[2]</value>
      <webElementGuid>5b2f80ca-8c70-4598-b4cd-b85664cf8d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appearance']/parent::*</value>
      <webElementGuid>d54dbf42-0c5b-481c-9a9b-5b96bdbd9ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/h2/button</value>
      <webElementGuid>5fe9b552-eb36-4dd7-ba3c-96400a33c145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Appearance
                ' or . = '
                    Appearance
                ')]</value>
      <webElementGuid>4ece52da-493d-4ff9-9602-c5ea6880d5b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
