<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click-on-image</name>
   <tag></tag>
   <elementGuidId>3b9ad8a2-9882-4113-b111-c1302523d008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;sl-block-content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eec8b9e2-7323-46bd-a408-5bea9639140b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Cropanchor</value>
      <webElementGuid>0bc34be5-e783-49c4-8856-7763cbbf1de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-direction</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>e3344c74-8c3b-4497-aa37-9a8b00a18cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mousedrag&quot;)/section[@class=&quot;present has-light-background&quot;]/div[@class=&quot;Crop-Container selected&quot;]/div[@class=&quot;sl-crop-block&quot;]/div[@class=&quot;anchor-wrapper&quot;]/div[@class=&quot;Cropanchor&quot;]</value>
      <webElementGuid>a66509b4-985f-49be-8fbe-9c40fbbd6d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mousedrag']/section/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>2bc1dc6d-49f0-4240-9eac-dba89eee9f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>3578a555-1771-4fa4-b06d-0e3bf5f8ef29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
