<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , clr-color-marker, , ))_cl_b70c39</name>
   <tag></tag>
   <elementGuidId>330d569f-e4ed-493c-816c-d08ed01b278f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clr-color-marker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='clr-color-marker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4293e239-35b5-460c-a383-a6fe3f821d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clr-color-marker</value>
      <webElementGuid>cd3b75b6-10a8-42c3-b289-0d0d57614f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clr-marker</value>
      <webElementGuid>abc9b3f2-cb51-4bff-ab7c-5ebcd9477f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b26ff76-3214-4d45-9811-78d034b335e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Saturation: 79. Brightness: 99.</value>
      <webElementGuid>12df08d3-cf04-4ae6-8eb7-221c8813401e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clr-color-marker&quot;)</value>
      <webElementGuid>0f332498-70bb-46f4-b46d-b1c3074d8010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='clr-color-marker']</value>
      <webElementGuid>ac072a56-d4a6-4153-bdc0-ed2e88b38de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clr-color-area']/div</value>
      <webElementGuid>3a989022-897d-45da-aaa2-c24bfade7366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[44]/div/div</value>
      <webElementGuid>f3a97bea-ca4c-44f5-afe1-473f4be4ad63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'clr-color-marker']</value>
      <webElementGuid>6f8a9aa7-596e-4284-aafe-063096dde191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
