<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Stop_sl-block-element</name>
   <tag></tag>
   <elementGuidId>771fc741-5509-49f3-b960-331da5d36b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sl-block-element</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mousedrag']/section/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2eaf5622-f233-4461-8046-058cc9acbdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/storage/composer/courses/6sbfybBbiOEl9qdK/files/hfNDpMY12chvPFnAiFo6tOCtSDBoUSWXOKoGhECg.png</value>
      <webElementGuid>34a2810d-6791-4c15-9b5c-8566e6cfe241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-block-element</value>
      <webElementGuid>74f806aa-d744-4af5-a006-46ef9661c8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-json</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;default_background_1.png&quot;,&quot;path&quot;:&quot;composer/courses/6sbfybBbiOEl9qdK/files/hfNDpMY12chvPFnAiFo6tOCtSDBoUSWXOKoGhECg.png&quot;,&quot;url&quot;:&quot;/storage/composer/courses/6sbfybBbiOEl9qdK/files/hfNDpMY12chvPFnAiFo6tOCtSDBoUSWXOKoGhECg.png&quot;,&quot;mine_type&quot;:&quot;image/png&quot;,&quot;extenssion&quot;:&quot;png&quot;,&quot;size&quot;:557991,&quot;preview&quot;:&quot;https://dev.cognispark.ai/storage/composer/courses/6sbfybBbiOEl9qdK/files/thumbnails/EWIyzNF2LPCMDy69.png&quot;,&quot;id&quot;:879,&quot;thumbnail_path&quot;:&quot;composer/courses/6sbfybBbiOEl9qdK/files/thumbnails/EWIyzNF2LPCMDy69.png&quot;,&quot;width&quot;:781,&quot;height&quot;:439}</value>
      <webElementGuid>53bb5b59-e4ba-4e6c-84e9-9c61eb0ba24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mousedrag&quot;)/section[@class=&quot;present has-light-background&quot;]/div[@class=&quot;sl-block focused border-dotted&quot;]/div[@class=&quot;sl-block-content&quot;]/img[@class=&quot;sl-block-element&quot;]</value>
      <webElementGuid>d4af58bf-3284-4ae5-b57d-6d57837d7c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mousedrag']/section/div/div/img</value>
      <webElementGuid>da0bd827-d78c-41ea-9649-1370c8971949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/img</value>
      <webElementGuid>b95dec24-94e8-42ab-9277-9f7a1181ea48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/storage/composer/courses/6sbfybBbiOEl9qdK/files/hfNDpMY12chvPFnAiFo6tOCtSDBoUSWXOKoGhECg.png']</value>
      <webElementGuid>3c52331b-2e71-440c-b722-f35f6ffc1d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
