<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radius_element-border-radios</name>
   <tag></tag>
   <elementGuidId>ce366e04-bc59-42bf-933b-3a27bcd78325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-border-radios</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-border-radios']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26ba829e-1fd5-4047-a8c3-e1245f2039a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8752c6de-3ce2-4e4b-834c-579b9c8de7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clr-inp-box</value>
      <webElementGuid>fb7001fa-2fed-4ae6-a5a2-f4cad6fb4620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-border-radios</value>
      <webElementGuid>9d9f4e10-6472-4eea-ba88-96e2916399b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c527ff9a-48d4-46dd-8554-ca2b4afebad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-border-radios&quot;)</value>
      <webElementGuid>c06023df-a367-49ac-91a3-f26123279290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-border-radios']</value>
      <webElementGuid>fb716708-b534-4dff-aa72-cd4f5690de74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div[2]/span[2]/div[2]/input</value>
      <webElementGuid>bf8f9643-80f8-449b-8c19-7882cb039f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]/div[2]/input</value>
      <webElementGuid>8e9fe362-71a9-4544-9884-48da4f21d1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'element-border-radios']</value>
      <webElementGuid>804cf18a-030e-4be7-89df-6d4e7a7d97b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
