<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Color_element-border-color</name>
   <tag></tag>
   <elementGuidId>18fedf69-5a7f-44d8-a831-0cc44a316f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-border-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-border-color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a53adab5-a0a5-45be-8b04-0f1b2329dff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91a35300-2653-4d38-932a-4e6d1b15c39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clr-inp</value>
      <webElementGuid>1daee195-61ab-4baa-98a8-dd8ac79fec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-border-color</value>
      <webElementGuid>70137851-723b-403b-804f-fd59e5493658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>#000</value>
      <webElementGuid>4acf1abf-4722-45d3-a95b-a5690bd358bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-border-color&quot;)</value>
      <webElementGuid>8b58c999-b7d7-488c-b855-b3d2b6c6afe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-border-color']</value>
      <webElementGuid>4ea109df-969a-4787-9552-be7e95d42855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div[2]/span/div/input</value>
      <webElementGuid>f3cf0d4e-c589-4b85-bed4-b975db5a00f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/div/input</value>
      <webElementGuid>78a0f637-7461-4429-b5b7-6052fdd78c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'element-border-color']</value>
      <webElementGuid>7d60b0b5-afb3-4273-ad2f-516eac2c1868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
