<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Border_element-border</name>
   <tag></tag>
   <elementGuidId>5f352de6-d535-4e55-9827-c011caeb4886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-border']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f41fcee-ed6a-41dc-b75a-de9fe0287447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a817093-8bb6-495b-b53c-5ec07eb21df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-border</value>
      <webElementGuid>9dc0cf2e-5b20-4e13-a251-4b0529561589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-border&quot;)</value>
      <webElementGuid>3f8514ea-0b2a-4b0a-8ab7-900ef71423c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-border']</value>
      <webElementGuid>2d478d52-7214-4861-875f-00aba0b8e380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/span[3]/input</value>
      <webElementGuid>852ac835-7262-41b4-8784-805fd43444c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>99805737-df10-4567-aa9a-bc541c7f9b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'element-border']</value>
      <webElementGuid>bee5ebe3-a5d4-4eb7-b31f-684b3a4fa585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
