<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Width_element-border-width</name>
   <tag></tag>
   <elementGuidId>32eb342b-d31d-42bb-b02e-25b00790bea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-border-width</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-border-width']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f68d7ba1-15b2-492d-82f6-bae2ba50562c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>50f25231-8dcd-4b46-aa81-1d7586be3321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clr-inp-box</value>
      <webElementGuid>dc7f7436-abf8-40f3-b67b-d2699d5ec2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-border-width</value>
      <webElementGuid>63c192aa-a505-4377-9c59-d2cf1feb3f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2196045c-b731-408a-91c7-c04f3d19308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f61f5402-eaa6-4349-b2b2-58e568e7e07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-border-width&quot;)</value>
      <webElementGuid>bbbe9ce9-a433-4859-b8fd-eb60a96cede9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-border-width']</value>
      <webElementGuid>5bf45b57-38ab-42b8-82ff-cd86f8e92500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div[2]/span[2]/div/input</value>
      <webElementGuid>7596cfba-2eac-46e8-86c3-17a50e98048b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span[2]/div/input</value>
      <webElementGuid>2c7132fa-a3ce-4df4-984e-38126a339f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'element-border-width']</value>
      <webElementGuid>13df8a7d-c6d6-4932-8151-074d0e8911be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
