<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload-image-button</name>
   <tag></tag>
   <elementGuidId>b7502bcf-7a12-4eeb-bc91-35a8b56c94b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.choose-file-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;upload-images&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b363318-e8cd-45ed-96f3-17f103f1b4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choose-file-btn</value>
      <webElementGuid>e3b8e8d6-080e-40fb-8c06-ae844819c5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('upload-images').click()</value>
      <webElementGuid>fe38f3bb-e7aa-4e21-9aac-2ac39a196407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose A File</value>
      <webElementGuid>844ec8d5-67c8-44ea-b7a4-e565a0196aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadImageTab&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;upload-area&quot;]/button[@class=&quot;choose-file-btn&quot;]</value>
      <webElementGuid>d0544d45-a728-4689-9b1a-4a15414e3249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;document.getElementById('upload-images').click()&quot;]</value>
      <webElementGuid>b2254423-e12c-46b7-914b-09c5365aa637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploadImageTab']/div/div/div/button</value>
      <webElementGuid>7a5b515c-96e2-4af8-b7f1-8cca50289820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(accepted files: jpg, jpeg, png upto 5MB)'])[1]/following::button[1]</value>
      <webElementGuid>c9007bf3-fa60-402f-ae60-88ec6dde40e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drag and drop'])[1]/following::button[1]</value>
      <webElementGuid>30ee4730-fe20-4d62-b970-940cfdf32525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::button[41]</value>
      <webElementGuid>6d572e9a-50e0-4559-82e6-dba049c35f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance'])[1]/preceding::button[42]</value>
      <webElementGuid>a5e7a0a2-6eb7-4a6f-80d7-c26dc39fb956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose A File']/parent::*</value>
      <webElementGuid>a85eefd2-65c3-4fa5-bf4e-a8392d93833c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>a034d5f2-8720-4d25-b4b0-7aed5bcf6774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Choose A File' or . = 'Choose A File')]</value>
      <webElementGuid>d21d0a2f-85b5-4ca5-b32c-e9616f6dd843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
