<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Using AI_1</name>
   <tag></tag>
   <elementGuidId>c2305f85-be66-4da8-b53e-c82b9b9a1e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gen_outcome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gen_outcome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c395d421-7fb3-4afe-840f-f0a6f4327317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ms-2 main-sl-btn</value>
      <webElementGuid>787077de-065d-4320-90b8-710efb94a448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gen_outcome</value>
      <webElementGuid>1ce3ab75-bff0-48a7-b3cb-98bb0522c674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>get_outcome()</value>
      <webElementGuid>0d1d5316-a2f1-4a42-a106-a1161e1091e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b89cbdbe-673f-4753-8b89-f1a7434d50ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Using AI</value>
      <webElementGuid>84fc402b-82d0-43c4-97dd-f10e5d2874af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gen_outcome&quot;)</value>
      <webElementGuid>835884ba-3dc5-4603-bf29-613a7ea90ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gen_outcome']</value>
      <webElementGuid>19563149-cd0f-4b2a-82f8-0ba25a3bf77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outcome']/span/button</value>
      <webElementGuid>1258b067-1af6-419b-b501-bd525bcc322d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Outcomes'])[1]/following::button[1]</value>
      <webElementGuid>11067573-ea65-440f-9fff-2a60ddb06231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Using AI'])[1]/following::button[1]</value>
      <webElementGuid>a047a05a-c581-46f9-aad8-f93c19f9668d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>8a37ff29-0d64-4fc6-87c4-3be2047122ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Continue'])[1]/preceding::button[2]</value>
      <webElementGuid>a0bc762a-8c62-4658-93fd-bda98ba72a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/button</value>
      <webElementGuid>ef54b0ee-67bf-42d7-92a2-afa333dc5723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gen_outcome' and @type = 'button' and (text() = 'Generate Using AI' or . = 'Generate Using AI')]</value>
      <webElementGuid>bb10fcaf-8120-4418-8274-a46590240d3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
