<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Course_1</name>
   <tag></tag>
   <elementGuidId>c34d284a-2649-49c2-a8be-825ac8f6b0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit_from_button_down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit_from_button_down']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2caef38-9ffd-4668-84b2-43e1630afef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6019b0b-62ff-4170-b668-ede129d93695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary submit_from</value>
      <webElementGuid>cb7a4ef3-b882-43f4-95f9-6695813195af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_from_button_down</value>
      <webElementGuid>9960c94f-7f92-4f84-a1a1-80538edb06b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Course </value>
      <webElementGuid>f14ce320-5983-440b-ab2b-56388bf1606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_from_button_down&quot;)</value>
      <webElementGuid>9d50c7d4-6841-4e72-80c9-9eb862fcc3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit_from_button_down']</value>
      <webElementGuid>0e6059db-e206-4157-b053-f0ae5d7ee30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='submit_from']/div[2]/div/div/div[2]/button</value>
      <webElementGuid>d42eadc4-32ed-45d1-a84a-328dee836784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Female)'])[25]/following::button[2]</value>
      <webElementGuid>06fb572d-873c-4a4c-ac38-eddb40ecd1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CogniSpark'])[1]/preceding::button[1]</value>
      <webElementGuid>7bca4b3e-7409-4ff2-8689-3629f8357b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate Course']/parent::*</value>
      <webElementGuid>a9d9b814-6fd2-470b-9bad-e6f63a13d8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>77c924de-858d-47c9-835e-a06b3ac4a77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'submit_from_button_down' and (text() = 'Generate Course ' or . = 'Generate Course ')]</value>
      <webElementGuid>031f1ea8-534d-497b-9be2-baff8a117376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
