<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Using AI</name>
   <tag></tag>
   <elementGuidId>2e64d28d-da1a-4486-ba3e-d41e08763cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gen_objective</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gen_objective']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>168ff7f0-bdad-4d9e-8a99-efb3a0f9ea36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ms-2 main-sl-btn </value>
      <webElementGuid>efbf35f3-7707-4692-ad28-cff5a51a300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>get_objective()</value>
      <webElementGuid>01a8814f-87b7-4a0f-bd1c-4d9f8ec9dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gen_objective</value>
      <webElementGuid>97c0a7c6-929f-4075-87a9-b165a854916d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8dcb3295-de45-446d-b063-0586ce4f141a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Using AI</value>
      <webElementGuid>8a835453-2237-443e-a8e1-a03d58c58767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gen_objective&quot;)</value>
      <webElementGuid>f529a207-a3d7-4dbc-b33f-16e4a5e87012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gen_objective']</value>
      <webElementGuid>b63e8fd3-76f7-4cee-a97d-e9f6a030797f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div/div/div[2]/span/button</value>
      <webElementGuid>bffc5530-a17c-4227-919c-4b98011c6548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Objectives'])[1]/following::button[1]</value>
      <webElementGuid>76c2dd55-1bff-460c-96d0-fd91f424562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Outcomes'])[1]/preceding::button[1]</value>
      <webElementGuid>29f42a50-dd6c-4c9d-bb16-6add35bb12c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Using AI'])[2]/preceding::button[1]</value>
      <webElementGuid>b2710fbb-cb40-4e8f-8fdc-23b499983a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate Using AI']/parent::*</value>
      <webElementGuid>5d080cc0-a759-40b6-92d4-e32f43643655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>4f6ddadb-be81-406d-bc7e-cf134dc9cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gen_objective' and @type = 'button' and (text() = 'Generate Using AI' or . = 'Generate Using AI')]</value>
      <webElementGuid>22bc3450-d4ff-4bdb-8b21-a8005e4d39a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
