<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Theme_myImg_1</name>
   <tag></tag>
   <elementGuidId>eab085cb-a013-4ebc-be16-71fdfd91a5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='myImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4bf9e5ce-319b-4763-bd29-98f889527e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vid-result Click-here img-fluid</value>
      <webElementGuid>ef4ec943-f14e-4cf4-8052-b26cfa6b1b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/storage/composer/theme/thumbnail-49.png</value>
      <webElementGuid>a9a18b40-4749-4db6-93f5-6cfc82d079b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AI voiceover</value>
      <webElementGuid>a05ac286-c502-45f0-922c-45fc46ff557e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myImg</value>
      <webElementGuid>32ab5f1e-c42e-4c46-bc76-ccb992578293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;theme_49&quot;)/span[@class=&quot;ratio ratio-16x9&quot;]/img[@id=&quot;myImg&quot;]</value>
      <webElementGuid>d53dc20a-a93f-413f-b43a-960112641dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='myImg']</value>
      <webElementGuid>d56c50a2-2952-41c0-a3d2-2b98107cdb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='theme_49']/span/img</value>
      <webElementGuid>5f68c819-1f01-4fbc-8a01-3ef6c8060d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AI voiceover']</value>
      <webElementGuid>ad8451c0-6306-452a-9741-7166a4b6e808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>0753c0f2-330a-4c8d-9845-911fd02a69a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/storage/composer/theme/thumbnail-49.png' and @alt = 'AI voiceover' and @id = 'myImg']</value>
      <webElementGuid>97d68af6-aa7a-4e02-99ad-c627a0f07ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
