<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Theme_myImg</name>
   <tag></tag>
   <elementGuidId>f57cceff-dbfa-42c6-a142-782f1ceca39f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#theme_46 > span.ratio.ratio-16x9 > #myImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='myImg'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5958e5b2-7dc6-432f-aa66-564e97871afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vid-result Click-here img-fluid</value>
      <webElementGuid>e4681e10-1c2c-4c04-a58b-5c399451424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/storage/composer/theme/thumbnail-46.png</value>
      <webElementGuid>acf70817-1a7e-4024-b085-2f40150ea49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AI voiceover</value>
      <webElementGuid>b746707f-76f0-4e44-ac53-99a3106ed5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myImg</value>
      <webElementGuid>8abfaf63-1e3a-4a23-8e74-cd3bc6704c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;theme_46&quot;)/span[@class=&quot;ratio ratio-16x9&quot;]/img[@id=&quot;myImg&quot;]</value>
      <webElementGuid>fdd18fa9-ca1f-403e-b24e-084abcdebc81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='myImg'])[4]</value>
      <webElementGuid>664403b2-2d7e-4428-adea-4b506f42a733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='theme_46']/span/img</value>
      <webElementGuid>993212b1-b01b-4e2c-9138-75eb8b4e1005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='AI voiceover'])[4]</value>
      <webElementGuid>7eb515b6-2a83-44ac-985b-ccf656630fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/img</value>
      <webElementGuid>b8579710-67d4-40d4-8637-d130911049f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/storage/composer/theme/thumbnail-46.png' and @alt = 'AI voiceover' and @id = 'myImg']</value>
      <webElementGuid>f4d37323-42b4-458c-9e32-0f3fe1e97222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
