<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remainingcharacters_title</name>
   <tag></tag>
   <elementGuidId>4009d0bc-92f5-4cb6-8af1-2ea62e9cc83e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4509bd-eb96-4af1-8d21-2757599beaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ee91b60-87be-4d1c-b2bf-cbcb53f044b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02017105-4ee4-430e-8d09-1417d67ca8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>a6264035-435e-497d-bb8b-793abed23764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>87ed7a3e-ecc0-4594-ba7e-fdfe9429371b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Course Title</value>
      <webElementGuid>cd89f4a7-8843-4924-a51b-ab07cbae16ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)</value>
      <webElementGuid>66590fc7-2d85-4f9e-a5b3-20f8b229eb01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title']</value>
      <webElementGuid>802bcf6c-1f4b-40cc-afb7-20a9f6f7dcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='obj_outc']/div/div/input</value>
      <webElementGuid>ab215055-786e-404c-bb82-18e037070e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>09ed9de8-6950-4f1c-87c2-440f9c17bfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'title' and @name = 'title' and @placeholder = 'Enter Course Title']</value>
      <webElementGuid>8875535d-4610-416a-b217-138b0e624b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
