<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoviceAdvanced BeginnerCompetentProf_e0f65a</name>
   <tag></tag>
   <elementGuidId>5781d766-d765-4f56-a493-d8ce906a30cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skilllevel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='skilllevel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4ecd97b-ab23-4b12-b46e-429db66752e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skilllevel</value>
      <webElementGuid>6c639f58-1a39-4433-9826-bb5843353ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skilllevel</value>
      <webElementGuid>eae2dd7e-7383-4378-88ec-b7605750db73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-box</value>
      <webElementGuid>9d2b74e7-a43f-47b5-9e73-8ebe23edf690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											</value>
      <webElementGuid>c5ca38d1-5382-4501-958a-72e550686e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skilllevel&quot;)</value>
      <webElementGuid>1fc53362-5d0e-4722-bf4e-4165bf89754e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='skilllevel']</value>
      <webElementGuid>55be56c9-ccdd-41eb-a723-1775b8be1d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='obj_outc']/div/div[2]/div/select</value>
      <webElementGuid>df5f3040-082e-4d63-87da-cebcb4dd8591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skill Level'])[1]/following::select[1]</value>
      <webElementGuid>7e74674c-62ea-435d-88fe-c6386c891685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Duration'])[1]/preceding::select[1]</value>
      <webElementGuid>0340accd-4372-476b-99f7-29a6a9eb64e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[2]</value>
      <webElementGuid>0d43651e-1bdf-46d6-ab87-e79f5d997417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1274c009-fca1-45cf-bd9b-265e3130111a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'skilllevel' and @name = 'skilllevel' and (text() = '
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											' or . = '
																			Novice
													Advanced Beginner
													Competent
													Proficient
													Expert
											')]</value>
      <webElementGuid>90e645d7-dcda-4640-86d6-9ad52dc3c502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
