<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_KATALON_add-slide</name>
   <tag></tag>
   <elementGuidId>812ba101-0478-4ec3-beb1-d6b1d0c4aa17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev.cognispark.ai/composer/svg/square-plus.svg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.add-slide</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac8ff1c1-07ae-4080-a05e-516992603f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.cognispark.ai/composer/svg/square-plus.svg</value>
      <webElementGuid>a7f6d27e-12ef-493e-9d5a-413fc22e438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tippy</name>
      <type>Main</type>
      <value>Add new slide</value>
      <webElementGuid>616f4ad3-ce15-4059-b25f-510302a199de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-slide</value>
      <webElementGuid>bcb1f151-f1c7-473e-acce-50bebb06ed58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sf-js-enabled reveal-full-page&quot;]/body[@class=&quot;reveal-viewport&quot;]/div[@class=&quot;com-slider intro editor&quot;]/div[@class=&quot;panel-container-vertical resizable&quot;]/div[@class=&quot;ui-slides panel-top resizable&quot;]/div[@class=&quot;reveal-viewport&quot;]/div[@class=&quot;reveal concave convex center focused has-light-background ready&quot;]/div[@class=&quot;botton-slide&quot;]/div[@class=&quot;option-no-add&quot;]/span[@class=&quot;add-sl&quot;]/img[@class=&quot;add-slide&quot;]</value>
      <webElementGuid>84ffd11d-7b76-4ef5-9d71-3651aa8634bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.cognispark.ai/composer/svg/square-plus.svg')]</value>
      <webElementGuid>3522e948-9324-42e3-a94b-e6fe4af3eb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[6]/img</value>
      <webElementGuid>62e7946f-03ff-4672-9c07-94ecaebadabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.cognispark.ai/composer/svg/square-plus.svg']</value>
      <webElementGuid>151e0aab-7c0d-4db1-8187-b6273dbfb174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
