<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Insert Video_form-control search-video-input</name>
   <tag></tag>
   <elementGuidId>1dcfdfb6-cb38-4109-aa87-4280c408d4ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[37]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.search-video-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41312f9b-ef08-43b6-9fcb-02846618ffa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8442db4-09f8-4982-9207-461ad2808aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-video-input</value>
      <webElementGuid>04d93cf7-f2c8-41dc-952b-1ff44843f5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Text input with dropdown button</value>
      <webElementGuid>37d94838-8a0a-4734-a6ed-4daf6c125f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Video</value>
      <webElementGuid>cf0707de-b097-44f6-975c-dfe4ac1e4dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchVideoTab&quot;)/div[@class=&quot;form-group mb-2&quot;]/div[@class=&quot;input-group search-drop&quot;]/input[@class=&quot;form-control search-video-input&quot;]</value>
      <webElementGuid>0c8e4139-a444-47f4-8ac3-912d6261fb26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[37]</value>
      <webElementGuid>f3ccbfe8-bf93-4b52-8323-d172b384ba08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchVideoTab']/div/div/input</value>
      <webElementGuid>1939dfd8-a9fd-4256-8fa5-4092a76a1201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>615064f3-717b-4879-b246-43010306d90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Video']</value>
      <webElementGuid>0382e93c-40e4-4e9d-abc6-b86d409bde03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
