<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>74a6ca5f-cfbb-4d6c-b6d3-b23c40bc39ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='canEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#canEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b6c16c4-ac71-44cb-8b33-9b45ee5d24e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>canEdit</value>
      <webElementGuid>9794e264-5872-4b23-9378-e42320107275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canEdit</value>
      <webElementGuid>7274e6f5-41cd-4b05-ae8f-a8fb0af788b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Yes
							No
                        </value>
      <webElementGuid>876d9754-b94a-497f-aa2b-0e7f9941d720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canEdit&quot;)</value>
      <webElementGuid>1caef9d5-3e6c-4261-bfee-b91d247373ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='canEdit']</value>
      <webElementGuid>83a89b04-7e0f-4c91-b4e5-8be11b7c6a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='slide_edit']/select</value>
      <webElementGuid>5a053d0b-abb6-48e4-9a94-c195a47754f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editable'])[1]/following::select[1]</value>
      <webElementGuid>25c857d1-75e4-499c-95de-66e609690627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import as it is'])[1]/following::select[1]</value>
      <webElementGuid>950a77de-6015-4893-a3f7-54542e295aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create course using AI?'])[1]/preceding::select[1]</value>
      <webElementGuid>e223ebbf-9ce4-4a7d-b059-d1621aae323c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/preceding::select[1]</value>
      <webElementGuid>cbf2cc58-8c62-4214-88f3-f3dae2e60ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>af25ddb4-afe7-4d62-920d-2708baa8eff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'canEdit' and @id = 'canEdit' and (text() = '
							Yes
							No
                        ' or . = '
							Yes
							No
                        ')]</value>
      <webElementGuid>457d20a2-e65f-4755-ae50-aa863237e768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
