<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_upload a file</name>
   <tag></tag>
   <elementGuidId>01f0348b-ed63-49df-aa14-0ece62523717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;import-course-media&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.filepond--label-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0cee35f3-efd8-4fc0-9b55-462212f8904a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filepond--label-action</value>
      <webElementGuid>cec00d02-2ff5-4960-a36f-29713356d80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>upload a file</value>
      <webElementGuid>995ed903-7cf3-478d-8ab5-9c9d7f970e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span-msg&quot;)/span[@class=&quot;filepond--label-action&quot;]</value>
      <webElementGuid>c564563c-3032-45f7-ae51-ae44c19f532d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span-msg']/span</value>
      <webElementGuid>13d96a60-da5f-4e20-ac3d-76080ec757af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a file'])[1]/following::span[3]</value>
      <webElementGuid>9cb1761a-e686-4e04-ba52-500c0adfd583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import as it is'])[1]/preceding::span[2]</value>
      <webElementGuid>6e9dd80e-d841-4975-bbd5-8fc5f3b6b989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='upload a file']/parent::*</value>
      <webElementGuid>5ca69ae7-63f6-4e8b-a12f-4107f8d6b11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>a9ba3214-5c5e-4cbd-ad0e-424d8fe4c430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'upload a file' or . = 'upload a file')]</value>
      <webElementGuid>cd5441c5-6c57-4d21-b6a5-43ddaa0629e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
